version: "3.9"

services:
  site-contato_db:
    image: postgres:12
    container_name: site-contato
    environment:
      POSTGRES_DB: site-contato_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}